version: '3'
services:
  app:
    container_name: python-exercise
    build: .
    volumes:
      - ../:/srv/
    environment:
      - TZ=Asia/Tokyo
    tty: true
    command: bash
    working_dir: /srv
